promise()
    .then(()=> faz algo)
    .catch((error) => lidar com o errro
)